apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deploy-1
  name: nginx-deploy-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deploy-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deploy-1
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
